#baseURL = 'https://kokenmetlisa.freedombox.be/'
baseURL = ''
languageCode = 'en-us'
title = 'Kokenmetlisa'

[menu]
[[menu.header]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.header]]
    name = 'Lunch'
    pageRef = '/lunch'
    weight = 20
[[menu.header]]
    name = 'Hoofdgerechten'
    pageRef = '/hoofdgerechten'
    weight = 30
[[menu.header]]
    name = 'Nagerechten'
    pageRef = '/nagerechten'
    weight = 40
[[menu.header]]
    name = 'Bijgerechten'
    pageRef = '/bijgerechten'
    weight = 50



[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
