# Get all dishes
GET http://localhost:8080/dishes
Content-Type: application/json

###

# Get a dish
GET http://localhost:8080/dishes/1
Content-Type: application/json

###

# Create a new dish
POST http://localhost:8080/dishes
Content-Type: application/json

{
  "name": "Spaghetti Carbonara",
  "description": "Classic Italian pasta with eggs, cheese, pancetta, and pepper.",
  "category": "Hoofdgerechten",
  "imageUrl": "https://kokenmetlisa.be/images/pinda-koekjes.png"
}

###

# Create a new dish
POST http://localhost:8080/dishes
Content-Type: application/json

{
  "name": "Pizza Margharitta",
  "description": "De meest basic pizza die er bestaat.",
  "category": "Hoofdgerechten",
  "imageUrl": "https://kokenmetlisa.be/images/pinda-koekjes.png"
}

###

GET http://localhost:8080/category
Content-Type: application/json

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "test2",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Hoofdgerechten"
}