# Get all dishes
GET http://localhost:8080/dishes
Content-Type: application/json

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "test123"
}

###

GET http://localhost:8080/health
Content-Type: application/json

###

GET http://localhost:8080/login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0OTA1MzMwMSwiZXhwIjoxNzQ5MDU2OTAxfQ.XqPx8Ft3LG7djLZ29GHBGUN2B1bFAAqVNq9gDzLx4aI
Content-Type: application/json


###

DELETE http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0OTAyMzk3MiwiZXhwIjoxNzQ5MDI3NTcyfQ.Zpv9MJ-x-n5cHIIztUBPp-JIsFtbSVzt9TB7jzPDbsI
Content-Type: application/json

{
  "username": "jan"
}


###
POST http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW4iLCJpYXQiOjE3NDgzNzUxNTAsImV4cCI6MTc0ODM3ODc1MH0.aX_H2h3yBj9vAuUBHYyusBQLQ8C51LkFg9vSPrlBgFE
Content-Type: application/json

{
  "username": "Levi",
  "password": "levi123",
  "role": "USER"
}

###

PUT http://localhost:8080/users/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMZXZpIiwiaWF0IjoxNzQ2NDcyMTA2LCJleHAiOjE3NDY0NzU3MDZ9.X-Eflyab-EdWlu76y3nLIfxi2Ah5R_eYW0jzC1vId0g
Content-Type: application/json

{
  "username": "Levi",
  "oldPassword": "levi123",
  "newPassword": "test1234"
}

###

GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0ODM3NTg0NSwiZXhwIjoxNzQ4Mzc5NDQ1fQ.42m7cpvEQkqOceKwQ9JpC1Og6kgPCdihjgn-OrsxbqU
Content-Type: application/json

###

# Get a dish
GET http://localhost:8080/dishes/2
Content-Type: application/json

###

# Create a new dish
POST http://localhost:8080/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW4yIiwiaWF0IjoxNzQ2NDcyMzgwLCJleHAiOjE3NDY0NzU5ODB9.m3NX1eVuVGiY4EN4QqFesu3J4AudxrO2PysDegTEU18
Content-Type: application/json

{
  "name": "Spaghetti Carbonara",
  "description": "Classic Italian pasta with eggs, cheese, pancetta, and pepper.",
  "category": "Hoofdgerechten",
  "imageUrl": "https://kokenmetlisa.be/images/pinda-koekjes.png"
}

###

# Create a new dish
POST http://localhost:8080/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW4iLCJpYXQiOjE3NDYxMDY2OTIsImV4cCI6MTc0NjExMDI5Mn0.zYXLzWwFkJpHia0zQE3gNlY_XIsZT5oGyGuPyXy0MPk
Content-Type: application/json

{
  "name": "Pizza Margharitta",
  "description": "De meest basic pizza die er bestaat.",
  "category": "Hoofdgerechten",
  "imageUrl": "https://kokenmetlisa.be/images/pinda-koekjes.png"
}

###

DELETE http://localhost:8080/dishes/1
Content-Type: application/json

###

GET http://localhost:8080/category
Content-Type: application/json

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "test2",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Lunch"
}

###

POST http://localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW4yIiwiaWF0IjoxNzQ2NDcyMzgwLCJleHAiOjE3NDY0NzU5ODB9.m3NX1eVuVGiY4EN4QqFesu3J4AudxrO2PysDegTEU18
Content-Type: application/json

{
"category": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Nagerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Bijgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Brood",
  "parentCategory": "Lunch"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Salades",
  "parentCategory": "Lunch"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Soep",
  "parentCategory": "Lunch"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Vleesgerechten",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Aardappelen",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Ovenschotels",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Pasta",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Risotto",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Couscous",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Rijst & Noedels",
  "parentCategory": "Hoofdgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Burgers & Wraps",
  "parentCategory": "Vleesgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Taart",
  "parentCategory": "Nagerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Dessert",
  "parentCategory": "Nagerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Koeken",
  "parentCategory": "Nagerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Sauzen",
  "parentCategory": "Bijgerechten"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "category": "Deeg",
  "parentCategory": "Bijgerechten"
}

###

DELETE http://localhost:8080/category
Content-Type: application/json

{
  "category": "hoofdgerechten"
}

###

GET http://localhost:8080/dishes/category/hoofdgerechten
Content-Type: application/json