CREATE TABLE public.categories (
    category character varying(255) NOT NULL,
    "position" integer NOT NULL,
    parent_category_category character varying(255)
);

CREATE TABLE public.dishes (
    id bigint NOT NULL,
    description character varying(10000) NOT NULL,
    image_name character varying(255),
    name character varying(255) NOT NULL,
    category_category character varying(255) NOT NULL
);

ALTER TABLE public.dishes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dishes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    username character varying(255) NOT NULL,
    password character varying(255),
    role character varying(255)
);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category);

ALTER TABLE ONLY public.dishes
    ADD CONSTRAINT dishes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fkbwml8h4ebs1252ixtbbewxuew FOREIGN KEY (parent_category_category) REFERENCES public.categories(category);

ALTER TABLE ONLY public.dishes
    ADD CONSTRAINT fkpjk1tscss4s2ab2a5tvn4t50x FOREIGN KEY (category_category) REFERENCES public.categories(category);
