-- =========================================
-- V4 - safe migrate (idempotent)
-- =========================================

CREATE TABLE IF NOT EXISTS public.categories (
                                                 name varchar(255) NOT NULL,
    "position" integer NOT NULL,
    parent_category_name varchar(255),
    CONSTRAINT categories_pkey PRIMARY KEY (name)
    );

ALTER TABLE public.categories
DROP CONSTRAINT IF EXISTS fk_categories_parent;

ALTER TABLE public.categories
    ADD CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_category_name)
            REFERENCES public.categories(name);

CREATE TABLE IF NOT EXISTS public.dishes (
                                             id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                             description varchar(10000) NOT NULL,
    image_name varchar(255),
    name varchar(255) NOT NULL,
    "position" integer NOT NULL,
    CONSTRAINT dishes_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.dishes_categories (
                                                        dish_id bigint NOT NULL,
                                                        categories_name varchar(255) NOT NULL
    );

ALTER TABLE public.dishes_categories
DROP CONSTRAINT IF EXISTS fk_dishes_categories_dish;

ALTER TABLE public.dishes_categories
    ADD CONSTRAINT fk_dishes_categories_dish
        FOREIGN KEY (dish_id)
            REFERENCES public.dishes(id);

ALTER TABLE public.dishes_categories
DROP CONSTRAINT IF EXISTS fk_dishes_categories_category;

ALTER TABLE public.dishes_categories
    ADD CONSTRAINT fk_dishes_categories_category
        FOREIGN KEY (categories_name)
            REFERENCES public.categories(name);

CREATE TABLE IF NOT EXISTS public.users (
                                            username varchar(255) NOT NULL,
    password varchar(255),
    role varchar(255),
    CONSTRAINT users_pkey PRIMARY KEY (username)
    );