services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: dishes_user
      POSTGRES_PASSWORD: dishes_password
      POSTGRES_DB: dishes
    ports:
      - 5433:5432
